name: Build unstable UI images when changes occur to UI tests

on:
  push:
    branches:
      - main
    paths:
      - ui.Dockerfile
      - pyproject.toml
      - testsuite/page_objects/**
      - testsuite/tests/singlecluster/ui/**
  workflow_dispatch:

env:
  IMG_REGISTRY_HOST: quay.io
  IMG_REGISTRY_ORG: kuadrant
  UI_IMG_NAME: testsuite-ui
  IMG_TAGS: unstable ${{ github.sha }}

jobs:
  build-unstable-ui:
    name: Build unstable UI images
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build unstable UI and sha images
        id: build-ui-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.UI_IMG_NAME }}
          tags: ${{ env.IMG_TAGS }}
          layers: true
          platforms: linux/amd64,linux/arm64
          containerfiles: |
            ./ui.Dockerfile

      - name: Push UI images to quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-ui-image.outputs.image }}
          tags: ${{ steps.build-ui-image.outputs.tags }}
          registry: ${{ env.IMG_REGISTRY_HOST }}/${{ env.IMG_REGISTRY_ORG }}
          username: ${{ secrets.IMG_REGISTRY_USERNAME }}
          password: ${{ secrets.IMG_REGISTRY_TOKEN }}
